### ISSUE TITLE
ScrollTopButton.js:15 prints "hi" in the console

### ISSUE THREAD

**Issue by Rafal-Majewski** [Uniwersytet-Gdanski/biological-dictionary-client#13]

**Comment by Rafal-Majewski** [comment]
it happens on mouse scroll btw

**Comment by Nicofisi** [comment]
Wouldn't it take you less time to delete it? You even found the line lol

https://user-images.githubusercontent.com/12614053/169719245-a780a53f-9744-46cb-856c-13055f953861.mp4

And stop invalidating your issues!
![image](https://user-images.githubusercontent.com/12614053/169719284-8a3843d4-d8f0-4d1e-91a0-5548630f4f27.png)

**Comment by Rafal-Majewski** [comment]
The line number was given as a part of the output in the developer console. I pasted it here as a todo task to fix while updating frontend the next time ;)

Also, sorry for misusing the labels :(
